use dblojinha;

CREATE TABLE VENDAS (
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
DATA DATETIME,
QUANTIDADE INT,
FATURADO BIT,
CODIGOCLIENTE INT,
CODIGOPRODUTO INT,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED
(
    [CODIGO]
    ) ON [PRIMARY], CONSTRAINT [FK_CODIGO_CLIENTES] FOREIGN KEY
    (
    [CODIGOCLIENTE]
    )REFERENCES [CLIENTES] ([CODIGO]
    ),
    CONSTRAINT [FK_CODIGO_PRODUTOS] FOREIGN KEY
    (
    [CODIGOPRODUTO]
    )REFERENCES [PRODUTOS] (
    [CODIGO]
    )
) ON [PRIMARY]
GO