use dblojinha;

CREATE TABLE PRODUTOS (
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
NOME VARCHAR(100),
PRECO VARCHAR(100),
ESTOQUE VARCHAR(20),
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED
(
    [CODIGO]
    ) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO PRODUTOS(NOME, PRECO, ESTOQUE)
VALUES('COMPUTADOR GAMER', 15000.00, 15);
 
INSERT INTO PRODUTOS(NOME, PRECO, ESTOQUE)
VALUES(' IMPRESSORA 3D', 5000.00, 10);

SELECT * FROM PRODUTOS;